### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by juhee0202** [ORIE4741/projects#48]
Good things
1. Very interesting topics! I have never seen data that has to do with sound. 
2. You guys have a clear topic, and a clear sense of goal that you are trying to achieve through this project.
3. I like that you guys clearly defined the input and output of your prediction algorithm.

Areas of Improvement
1. What kind of tools or software are you going to use to process the voice samples?
2. You could describe in more detail about the algorithms or methods that you will use to classify the voices into different genders.
3. Does the data set have multiple dimensions? what are some fields that you need to consider when you are categorizing people's voices into genders? Have you thought about outliers?

**Comment by madeleineudell** [comment]
Please raise this issue on the project group's repo, not the class repo.
