### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by kh522** [ORIE4741/projects#49]
I think that this project proposal is a very interesting topic to research in. I like the project idea, and how the subset of data should be able to give concrete conclusions. Something else that I like about this proposal was that it is a practical area that can be useful to others. Some things that I think that this proposal can be improved upon is to put more details in it. I would like to see what kind of data the dataset has in it, and what methods they are thinking of using in order to make a classifier that can predict such things. I would also like to see a timeline in when they think they can get certain things done.

**Comment by madeleineudell** [comment]
Please raise this issue on the project group's repo, not the class repo.
