### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by kh522** [ORIE4741/projects#50]
I really enjoyed this proposal, as it was very detailed. I particularly enjoyed the background description, the formulation of the problem and a pretty detailed description of the data set as well as possible approaches in dealing with the problem. I think that the proposal should specify that the model that they train on is limited to NYC, since that is a limitation with their data. I also think that the proposal can also be improved on by adding in how they decide to choose certain variables to have greater influence over others in the model (ie which variables are not relevant to housing prices). Lastly I believe that the proposal can be improved if you can propose how you can have other people realistically use your model. Overall, I think that the proposal is pretty solid.

**Comment by madeleineudell** [comment]
Please raise this issue on the project group's repo, not the class repo.
