### ISSUE TITLE
Peer review (sj393)

### ISSUE THREAD

**Issue by sjaroslawski** [ORIE4741/projects#51]
This project seems like it could be very useful for Expedia.  I like the thought of expanding Expedia to recommend bars and restaurants nearby as that would be another potential avenue for revenue for Expedia.  The challenge will be to create a smart machine learning algorithm.  I imagine that many companies are working hard to create hotel recommendation algorithms, so there is a high bar to surpass in the industry already.  This project will be very interesting and if done well could be extremely popular and useful for companies like Expedia.  Perhaps you could also include recommendations for groups.  You could take everyone in the group's preferences and suggest a hotel that would best suit everyone's needs.  Overall, this project seems interesting and has the potential to be very useful.

**Comment by madeleineudell** [comment]
Please raise this issue on the project group's repo, not the class repo.
